name: "Cloudanix Image Scanner"
description: "Image Scanner Scans container images for vulnerabilities with Policy based evaluation"
author: "Cloudanix"
branding:
  icon: "activity"
  color: "blue"
inputs:
  image:
    description: "Image to Scan"
    required: true
  authz-token:
    description: "Cloudanix Authorization Token"
    required: true
  identifier:
    description: "Cloudanix Account Identifier"
    required: true
  enable-policy-evaluation:
    description: "Enable Policy Evaluation"
    required: false
    default: "true"
  debug-mode:
    description: "Enable Debug Mode"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-a ${{ inputs.image }}"
    - "-b ${{ inputs.authz-token }}"
    - "-c ${{ inputs.identifier }}"
    - "-d ${{ inputs.enable-policy-evaluation }}"
    - "-e ${{ inputs.debug-mode }}"
