name: "Cloudanix Image Scanner"
description: "Image Scanner Scans container images for vulnerabilities"
author: "Cloudanix"
branding:
  icon: "activity"
  color: "blue"
inputs:
  image:
    description: "image reference(for backward compatibility)"
    required: true
  authz-token:
    description: "Cloudanix Authorization Token"
    required: true
  identifier:
    description: "Cloudanix Account Identifier"
    required: true
  debug-mode:
    description: "Enable Debug Mode"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-a ${{ inputs.image }}"
    - "-b ${{ inputs.authz-token }}"
    - "-c ${{ inputs.identifier }}"
    - "-d ${{ inputs.debug-mode }}"
